#server:
#  port: 9090
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: accounts-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/accounts/**
#        - id: loans-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/loans/**
#        - id: greet-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/greet/**
#    discovery:
#      locator:
#        enabled: true
#        lower-case-service-id: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
